source 'https://rubygems.org'
ruby '2.6.6'

# Required gems to build Rails Guides (same as rails/rails)
gem 'erubi'
gem 'rack-test'
gem 'rails-html-sanitizer'
gem 'rake'
group :doc do
  gem 'kindlerb' # , "~> 1.2.0"
  gem 'redcarpet' # , "~> 3.2.3", platforms: :ruby
  gem 'sdoc'
  gem 'w3c_validators'
end

# Required gems to host yasslab/railsguides.jp
gem 'jekyll'
gem 'kramdown'
gem 'rack-jekyll'

# Test HTML files by: `bundle exec rake test`
# Required as well in production to check deployment
gem 'html-proofer'

group :development do
  gem 'docset' # For generating docset (Dash)

  # TODO: We don't use GTT now. Delete this line
  #       with other GTT-associated codes.
  # gem "gtt-downloader"
end

group :development, :test do
  gem 'pry-byebug' # For debugging codes
end

group :test do
  # Required to exec: `bundle exec rspec spec/features/`
  gem 'capybara'
  gem 'rspec'
  gem 'turnip'
end

group :production do
  # Enable HTTP caching for Rack-based applications
  gem 'rack-cache' # , "~> 1.2"

  # Monitoring tools
  gem 'newrelic_rpm'

  # SSL in Production
  gem 'acme_challenge'
  gem 'puma'
  gem 'rack-contrib'
  gem 'rack-rewrite' # , "~> 1.5.0"
end
