source 'https://rubygems.org'
ruby "2.5.1"

# Required gems to build Rails Guides (same as rails/rails)
gem "rake"
gem 'rails-html-sanitizer'
gem 'erubi'
group :doc do
  #gem "sdoc", github: "robin850/sdoc", branch: "upgrade"
  gem "sdoc"
  gem "redcarpet", "~> 3.2.3", platforms: :ruby
  gem "w3c_validators"
  gem "kindlerb", "~> 1.2.0"
end

# Required gems to build yasslab/railsguides.jp (newly added)
gem "jekyll"
gem "rack-jekyll"
gem "kramdown"
gem "puma"
gem 'pry'

# Gems to generate RailsGuides HTML from MD
gem "rack-cache", "~> 1.2"

# Monitoring tools
gem "newrelic_rpm"

# SSL in Production
gem "acme_challenge"
gem "rack-rewrite", "~> 1.5.0"
gem "rack-contrib"

# Testing links by hand
gem "html-proofer"

group :development do
  # Generate docset
  gem "docset"

  # TODO: We don't use GTT now. Delete this line
  #       with other GTT-associated codes.
  #gem "gtt-downloader"
end

group :development, :test do
  gem "rb-readline"
  gem "pry-byebug"
end

group :test do
  gem "rspec"
  gem "turnip"
  gem "wraith"
end
